insert into ads (user_id, title, description, price, `condition`, platform, genre) values (32, 'Resident Evil 2', 'Embark on an epic adventure', 272.82, 'new', 'Nintendo Switch', 'Fighting');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (36, 'Final Fantasy', 'Unleash your inner hero', 845.99, 'new', 'Xbox One', 'Adventure');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (21, 'Dark Souls', 'Embark on an epic adventure', 985.63, 'new', 'Mobile', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (29, 'Okami', 'Engage in intense multiplayer battles', 706.58, 'used', 'Sega Saturn', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (81, 'The Elder Scrolls V: Skyrim', 'Engage in intense multiplayer battles', 842.31, 'used', 'PlayStation 2', 'Shooter');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (72, 'Duck Hunt', 'Experience thrilling gameplay', 181.11, 'used', 'PlayStation 2', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (88, 'The Legend of Zelda', 'Embark on an epic adventure', 493.78, 'used', 'PlayStation', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (32, 'Mega Man', 'Engage in intense multiplayer battles', 55.87, 'used', 'Xbox', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (38, 'Metal Gear Solid', 'Master challenging puzzles', 157.73, 'new', 'PC', 'Strategy');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (36, 'Resident Evil 4', 'Engage in intense multiplayer battles', 216.6, 'used', 'Nintendo 64', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (42, 'Metal Gear Solid 2: Sons of Liberty', 'Unleash your inner hero', 644.53, 'new', 'PlayStation 2', 'Strategy');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (60, 'Red Dead Redemption', 'Unleash your inner hero', 478.45, 'used', 'Sega Saturn', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (12, 'The Elder Scrolls V: Skyrim', 'Immerse yourself in a captivating world', 317.97, 'new', 'Nintendo Switch', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (38, 'Portal', 'Unleash your inner hero', 993.1, 'new', 'Xbox One', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (70, 'Final Fantasy IX', 'Immerse yourself in a captivating world', 635.3, 'new', 'Xbox', 'RPG');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (40, 'Street Fighter II', 'Embark on an epic adventure', 494.64, 'new', 'PC', 'Adventure');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (56, 'Mass Effect', 'Master challenging puzzles', 429.87, 'new', 'Sega Saturn', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (39, 'Fallout 3', 'Master challenging puzzles', 849.47, 'new', 'PlayStation', 'RPG');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (8, 'Super Smash Bros. Melee', 'Immerse yourself in a captivating world', 16.24, 'used', 'Sega Saturn', 'Adventure');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (88, 'Resident Evil 2', 'Immerse yourself in a captivating world', 981.81, 'used', 'Nintendo Switch', 'Shooter');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (7, 'Silent Hill', 'Embark on an epic adventure', 496.73, 'new', 'Nintendo 64', 'Shooter');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (30, 'Super Smash Bros.', 'Master challenging puzzles', 943.16, 'new', 'Mobile', 'Arcade');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (18, 'Dota 2', 'Immerse yourself in a captivating world', 89.73, 'new', 'Nintendo 64', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (46, 'BioShock Infinite', 'Engage in intense multiplayer battles', 37.48, 'used', 'Xbox', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (85, 'Super Metroid', 'Master challenging puzzles', 888.79, 'used', 'Mobile', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (76, 'Kingdom Hearts', 'Unleash your inner hero', 366.47, 'new', 'Nintendo Switch', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (74, 'Duck Hunt', 'Master challenging puzzles', 784.66, 'new', 'Xbox', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (83, 'Call of Duty: Modern Warfare', 'Master challenging puzzles', 342.46, 'new', 'Sega Saturn', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (13, 'Kingdom Hearts', 'Immerse yourself in a captivating world', 410.81, 'used', 'Sega Genesis', 'Adventure');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (66, 'Minecraft', 'Immerse yourself in a captivating world', 534.24, 'new', 'PlayStation', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (37, 'League of Legends', 'Engage in intense multiplayer battles', 246.0, 'used', 'Nintendo 64', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (82, 'Guitar Hero', 'Experience thrilling gameplay', 497.43, 'used', 'Nintendo 64', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (11, 'Dota 2', 'Experience thrilling gameplay', 927.02, 'new', 'Sega Saturn', 'Shooter');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (85, 'Mario Kart 64', 'Unleash your inner hero', 740.5, 'used', 'Xbox One', 'Adventure');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (18, 'Bubble Bobble', 'Unleash your inner hero', 537.16, 'new', 'Super Nintendo', 'Shooter');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (89, 'Bloodborne', 'Embark on an epic adventure', 876.21, 'new', 'PlayStation 2', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (83, 'Donkey Kong 64', 'Master challenging puzzles', 875.34, 'new', 'Nintendo 64', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (63, 'Super Mario Kart', 'Embark on an epic adventure', 993.78, 'used', 'Nintendo Switch', 'RPG');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (37, 'Resident Evil 2', 'Embark on an epic adventure', 295.69, 'used', 'Super Nintendo', 'Strategy');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (4, 'Fortnite', 'Embark on an epic adventure', 531.86, 'new', 'Nintendo 64', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (63, 'Counter-Strike: Global Offensive', 'Unleash your inner hero', 797.81, 'new', 'Sega Saturn', 'RPG');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (27, 'Dark Souls', 'Master challenging puzzles', 586.08, 'used', 'Xbox', 'Fighting');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (6, 'The Legend of Zelda', 'Immerse yourself in a captivating world', 610.75, 'new', 'Super Nintendo', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (79, 'Grand Theft Auto III', 'Experience thrilling gameplay', 266.04, 'used', 'Sega Saturn', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (90, 'League of Legends', 'Experience thrilling gameplay', 150.25, 'new', 'Super Nintendo', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (10, 'Spyro the Dragon', 'Unleash your inner hero', 683.88, 'new', 'Sega Genesis', 'Strategy');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (54, 'Diablo II', 'Immerse yourself in a captivating world', 171.48, 'new', 'Mobile', 'Strategy');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (79, 'BioShock Infinite', 'Embark on an epic adventure', 497.19, 'new', 'Sega Saturn', 'Adventure');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (15, 'Minecraft', 'Engage in intense multiplayer battles', 828.92, 'new', 'PlayStation', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (20, 'Duck Hunt', 'Unleash your inner hero', 44.19, 'new', 'Xbox', 'Fighting');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (11, 'Crash Team Racing', 'Unleash your inner hero', 167.03, 'used', 'PlayStation 2', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (45, 'Perfect Dark', 'Embark on an epic adventure', 423.75, 'used', 'Super Nintendo', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (45, 'Mortal Kombat', 'Unleash your inner hero', 629.32, 'used', 'Super Nintendo', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (42, 'Space Invaders', 'Engage in intense multiplayer battles', 703.71, 'new', 'PlayStation 2', 'RPG');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (22, 'The Last of Us', 'Master challenging puzzles', 898.32, 'used', 'Sega Genesis', 'Sports');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (50, 'Donkey Kong', 'Embark on an epic adventure', 720.29, 'used', 'PlayStation', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (50, 'Metal Gear Solid', 'Immerse yourself in a captivating world', 160.7, 'used', 'PC', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (86, 'Red Dead Redemption', 'Experience thrilling gameplay', 688.89, 'new', 'Sega Saturn', 'Sports');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (23, 'Overwatch', 'Engage in intense multiplayer battles', 713.14, 'new', 'Xbox One', 'Arcade');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (16, 'Donkey Kong 64', 'Engage in intense multiplayer battles', 676.47, 'new', 'Sega Saturn', 'Arcade');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (50, 'Counter-Strike: Global Offensive', 'Immerse yourself in a captivating world', 813.19, 'new', 'Super Nintendo', 'Shooter');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (52, 'The Witcher 3: Wild Hunt', 'Embark on an epic adventure', 428.71, 'new', 'Super Nintendo', 'Shooter');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (30, 'The Witcher 3: Wild Hunt', 'Engage in intense multiplayer battles', 828.73, 'new', 'Xbox', 'RPG');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (76, 'Okami', 'Master challenging puzzles', 958.27, 'used', 'Sega Saturn', 'Adventure');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (64, 'The Legend of Zelda: Ocarina of Time', 'Immerse yourself in a captivating world', 125.66, 'new', 'Super Nintendo', 'Strategy');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (24, 'Halo: Combat Evolved', 'Embark on an epic adventure', 196.02, 'used', 'Mobile', 'Shooter');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (46, 'Diablo II', 'Experience thrilling gameplay', 675.61, 'new', 'Xbox', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (31, 'Super Metroid', 'Unleash your inner hero', 165.41, 'new', 'PlayStation 2', 'Fighting');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (81, 'Perfect Dark', 'Engage in intense multiplayer battles', 346.4, 'new', 'PC', 'Sports');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (84, 'Super Mario 64', 'Experience thrilling gameplay', 108.58, 'new', 'Nintendo Switch', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (35, 'Rayman', 'Embark on an epic adventure', 604.78, 'new', 'PlayStation 2', 'Sports');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (35, 'Overwatch', 'Unleash your inner hero', 643.79, 'new', 'PC', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (47, 'Mass Effect', 'Immerse yourself in a captivating world', 382.37, 'used', 'Mobile', 'Sports');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (47, 'Star Fox 64', 'Master challenging puzzles', 866.34, 'new', 'Xbox', 'Strategy');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (66, 'Overwatch', 'Unleash your inner hero', 959.46, 'new', 'Sega Genesis', 'Arcade');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (19, 'Metroid', 'Experience thrilling gameplay', 476.09, 'used', 'PC', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (90, 'Metal Gear Solid', 'Experience thrilling gameplay', 208.56, 'new', 'Xbox One', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (83, 'The Last of Us', 'Experience thrilling gameplay', 387.48, 'used', 'Nintendo Switch', 'Arcade');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (78, 'Fortnite', 'Embark on an epic adventure', 37.68, 'used', 'Sega Saturn', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (37, 'League of Legends', 'Engage in intense multiplayer battles', 876.26, 'used', 'PlayStation', 'Fighting');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (77, 'StarCraft', 'Unleash your inner hero', 807.61, 'new', 'Xbox One', 'Fighting');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (68, 'Okami', 'Engage in intense multiplayer battles', 528.16, 'used', 'Xbox', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (22, 'The Witcher 3: Wild Hunt', 'Master challenging puzzles', 519.14, 'used', 'Sega Saturn', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (88, 'Super Mario World', 'Engage in intense multiplayer battles', 641.72, 'used', 'PlayStation', 'Strategy');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (21, 'Gran Turismo', 'Immerse yourself in a captivating world', 505.3, 'used', 'Xbox One', 'Strategy');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (6, 'The Legend of Zelda: Ocarina of Time', 'Immerse yourself in a captivating world', 240.95, 'used', 'Xbox One', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (73, 'Call of Duty: Modern Warfare', 'Engage in intense multiplayer battles', 994.56, 'new', 'Sega Saturn', 'RPG');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (5, 'Gears of War', 'Immerse yourself in a captivating world', 324.99, 'used', 'Xbox One', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (61, 'God of War II', 'Embark on an epic adventure', 152.72, 'new', 'Sega Genesis', 'Fighting');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (71, 'Minecraft', 'Master challenging puzzles', 516.72, 'used', 'Sega Saturn', 'RPG');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (17, 'Crash Bandicoot', 'Unleash your inner hero', 125.71, 'new', 'Nintendo 64', 'RPG');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (22, 'Mario Party', 'Experience thrilling gameplay', 420.85, 'new', 'Mobile', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (16, 'Devil May Cry', 'Immerse yourself in a captivating world', 56.66, 'new', 'Sega Saturn', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (27, 'Red Dead Redemption', 'Embark on an epic adventure', 381.09, 'used', 'Sega Genesis', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (11, 'Kingdom Hearts', 'Master challenging puzzles', 615.57, 'used', 'Nintendo 64', 'Strategy');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (5, 'Diablo II', 'Embark on an epic adventure', 512.36, 'new', 'PlayStation', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (60, 'GoldenEye 007', 'Immerse yourself in a captivating world', 888.27, 'new', 'Sega Genesis', 'Adventure');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (71, 'Star Fox 64', 'Master challenging puzzles', 776.64, 'used', 'Super Nintendo', 'Shooter');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (31, 'Pokémon Stadium', 'Experience thrilling gameplay', 796.71, 'used', 'PC', 'Adventure');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (62, 'God of War', 'Master challenging puzzles', 509.89, 'new', 'Super Nintendo', 'Arcade');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (74, 'Super Metroid', 'Embark on an epic adventure', 61.16, 'used', 'Nintendo Switch', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (17, 'Galaga', 'Engage in intense multiplayer battles', 40.69, 'new', 'PlayStation', 'RPG');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (50, 'BioShock Infinite', 'Master challenging puzzles', 128.86, 'used', 'Mobile', 'Arcade');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (81, 'Fortnite', 'Immerse yourself in a captivating world', 102.92, 'new', 'Mobile', 'Strategy');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (27, 'The Witcher 3: Wild Hunt', 'Master challenging puzzles', 714.36, 'used', 'PC', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (81, 'World of Warcraft', 'Master challenging puzzles', 601.56, 'used', 'Nintendo Switch', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (87, 'Metal Gear Solid 2: Sons of Liberty', 'Embark on an epic adventure', 978.3, 'used', 'Mobile', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (22, 'Resident Evil', 'Master challenging puzzles', 281.96, 'new', 'Nintendo Switch', 'RPG');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (36, 'Half-Life', 'Unleash your inner hero', 244.05, 'new', 'Nintendo 64', 'Shooter');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (29, 'Call of Duty: Modern Warfare', 'Immerse yourself in a captivating world', 831.24, 'used', 'Xbox One', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (37, 'Metroid', 'Unleash your inner hero', 609.2, 'new', 'Super Nintendo', 'Strategy');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (73, 'League of Legends', 'Engage in intense multiplayer battles', 473.43, 'used', 'PC', 'Adventure');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (6, 'League of Legends', 'Master challenging puzzles', 414.91, 'new', 'PlayStation', 'Adventure');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (42, 'Crash Team Racing', 'Experience thrilling gameplay', 221.64, 'new', 'Sega Genesis', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (56, 'The Legend of Zelda: Ocarina of Time', 'Master challenging puzzles', 733.07, 'used', 'Nintendo 64', 'Fighting');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (83, 'Guitar Hero', 'Immerse yourself in a captivating world', 675.77, 'used', 'Mobile', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (81, 'Super Mario World', 'Engage in intense multiplayer battles', 398.84, 'used', 'Sega Genesis', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (37, 'Mortal Kombat', 'Immerse yourself in a captivating world', 363.63, 'new', 'Nintendo 64', 'Strategy');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (75, 'Red Dead Redemption', 'Embark on an epic adventure', 667.04, 'new', 'PlayStation 2', 'Shooter');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (22, 'Bioshock', 'Master challenging puzzles', 986.77, 'used', 'Sega Genesis', 'Sports');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (69, 'Resident Evil 2', 'Immerse yourself in a captivating world', 322.16, 'new', 'Mobile', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (11, 'Half-Life', 'Immerse yourself in a captivating world', 627.35, 'used', 'Nintendo Switch', 'Fighting');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (67, 'BioShock Infinite', 'Experience thrilling gameplay', 497.85, 'new', 'PC', 'Fighting');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (41, 'League of Legends', 'Unleash your inner hero', 201.61, 'new', 'PlayStation 2', 'Fighting');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (60, 'Call of Duty: Modern Warfare', 'Master challenging puzzles', 908.08, 'new', 'PlayStation 2', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (6, 'Mega Man', 'Engage in intense multiplayer battles', 27.95, 'used', 'PC', 'Arcade');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (21, 'World of Warcraft', 'Immerse yourself in a captivating world', 171.75, 'new', 'PlayStation 2', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (20, 'Perfect Dark', 'Embark on an epic adventure', 824.17, 'new', 'PlayStation 2', 'Sports');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (10, 'Super Mario Bros.', 'Engage in intense multiplayer battles', 499.74, 'new', 'PC', 'Sports');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (73, 'Halo: Combat Evolved', 'Unleash your inner hero', 426.84, 'new', 'Super Nintendo', 'Strategy');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (25, 'League of Legends', 'Experience thrilling gameplay', 626.65, 'used', 'Nintendo Switch', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (9, 'Devil May Cry', 'Immerse yourself in a captivating world', 198.37, 'used', 'Xbox', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (40, 'Call of Duty: Modern Warfare', 'Master challenging puzzles', 233.62, 'used', 'PlayStation 2', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (67, 'StarCraft', 'Immerse yourself in a captivating world', 788.63, 'new', 'Nintendo 64', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (60, 'Super Mario Bros.', 'Experience thrilling gameplay', 395.03, 'new', 'Sega Genesis', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (6, 'Galaga', 'Immerse yourself in a captivating world', 858.38, 'used', 'Nintendo Switch', 'Arcade');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (18, 'Overwatch', 'Master challenging puzzles', 981.33, 'used', 'Nintendo Switch', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (59, 'Overwatch', 'Master challenging puzzles', 102.57, 'used', 'PC', 'RPG');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (53, 'Sonic the Hedgehog', 'Immerse yourself in a captivating world', 561.0, 'used', 'Xbox One', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (80, 'Devil May Cry', 'Experience thrilling gameplay', 187.82, 'used', 'Mobile', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (16, 'Half-Life', 'Unleash your inner hero', 896.88, 'new', 'PC', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (54, 'Chrono Trigger', 'Unleash your inner hero', 392.31, 'used', 'PC', 'RPG');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (4, 'Super Metroid', 'Immerse yourself in a captivating world', 602.53, 'new', 'PlayStation 2', 'Sports');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (89, 'Call of Duty: Modern Warfare', 'Unleash your inner hero', 483.89, 'used', 'Sega Saturn', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (81, 'The Witcher 3: Wild Hunt', 'Master challenging puzzles', 904.53, 'used', 'Nintendo Switch', 'RPG');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (25, 'Tony Hawk''s Pro Skater 2', 'Immerse yourself in a captivating world', 228.48, 'used', 'PlayStation', 'Sports');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (4, 'Rayman', 'Embark on an epic adventure', 104.51, 'used', 'Xbox', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (75, 'Silent Hill', 'Unleash your inner hero', 49.82, 'new', 'Nintendo 64', 'RPG');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (39, 'Super Mario Bros.', 'Experience thrilling gameplay', 710.81, 'used', 'PC', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (83, 'World of Warcraft', 'Embark on an epic adventure', 484.85, 'used', 'PlayStation', 'Fighting');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (21, 'Okami', 'Master challenging puzzles', 894.91, 'used', 'Sega Genesis', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (36, 'Metal Gear Solid', 'Immerse yourself in a captivating world', 876.05, 'new', 'PlayStation 2', 'Arcade');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (63, 'League of Legends', 'Embark on an epic adventure', 381.79, 'new', 'Xbox', 'Strategy');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (5, 'League of Legends', 'Embark on an epic adventure', 431.76, 'used', 'Nintendo Switch', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (40, 'Space Invaders', 'Engage in intense multiplayer battles', 231.12, 'new', 'PlayStation 2', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (66, 'Metroid', 'Immerse yourself in a captivating world', 248.31, 'used', 'Sega Saturn', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (29, 'Okami', 'Unleash your inner hero', 558.71, 'used', 'Sega Genesis', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (76, 'Bioshock', 'Master challenging puzzles', 606.74, 'used', 'PlayStation', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (73, 'Resident Evil 2', 'Experience thrilling gameplay', 355.09, 'new', 'PC', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (30, 'Halo: Combat Evolved', 'Engage in intense multiplayer battles', 23.51, 'used', 'Super Nintendo', 'Fighting');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (31, 'Dark Souls', 'Experience thrilling gameplay', 585.18, 'used', 'PC', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (37, 'Super Mario Bros.', 'Embark on an epic adventure', 618.37, 'used', 'Sega Saturn', 'RPG');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (76, 'Metal Gear Solid', 'Experience thrilling gameplay', 391.11, 'used', 'PC', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (58, 'Sonic the Hedgehog', 'Embark on an epic adventure', 841.07, 'used', 'Xbox One', 'Fighting');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (57, 'Street Fighter II', 'Unleash your inner hero', 885.0, 'new', 'PlayStation 2', 'Adventure');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (37, 'Galaga', 'Experience thrilling gameplay', 175.26, 'new', 'PlayStation', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (79, 'Crash Bandicoot', 'Embark on an epic adventure', 187.67, 'used', 'Sega Saturn', 'Adventure');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (84, 'Silent Hill', 'Experience thrilling gameplay', 206.77, 'new', 'Sega Genesis', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (56, 'Super Smash Bros. Melee', 'Immerse yourself in a captivating world', 223.02, 'used', 'Nintendo Switch', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (76, 'BioShock Infinite', 'Unleash your inner hero', 306.67, 'new', 'Sega Saturn', 'Sports');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (58, 'Pokémon Stadium', 'Engage in intense multiplayer battles', 399.02, 'used', 'Nintendo 64', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (77, 'World of Warcraft', 'Master challenging puzzles', 22.47, 'used', 'Nintendo Switch', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (45, 'Castlevania', 'Embark on an epic adventure', 472.28, 'used', 'Xbox', 'Strategy');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (4, 'Rayman', 'Experience thrilling gameplay', 471.08, 'used', 'Sega Genesis', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (84, 'Banjo-Kazooie', 'Master challenging puzzles', 12.42, 'new', 'PC', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (23, 'Portal', 'Unleash your inner hero', 217.37, 'new', 'Sega Saturn', 'Arcade');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (52, 'Diablo II', 'Unleash your inner hero', 226.71, 'used', 'PC', 'Arcade');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (12, 'Bioshock', 'Immerse yourself in a captivating world', 401.96, 'used', 'PlayStation', 'Strategy');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (71, 'Golden Axe', 'Engage in intense multiplayer battles', 377.13, 'new', 'Nintendo Switch', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (74, 'Mario Party', 'Immerse yourself in a captivating world', 909.74, 'new', 'Sega Saturn', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (47, 'Fallout 3', 'Experience thrilling gameplay', 150.86, 'used', 'Xbox One', 'Arcade');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (19, 'Super Mario Kart', 'Experience thrilling gameplay', 850.87, 'new', 'PlayStation 2', 'Fighting');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (65, 'Portal', 'Master challenging puzzles', 603.34, 'new', 'Nintendo Switch', 'Simulation');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (28, 'Contra', 'Master challenging puzzles', 856.89, 'used', 'Sega Saturn', 'RPG');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (50, 'Call of Duty: Modern Warfare', 'Immerse yourself in a captivating world', 471.86, 'new', 'PC', 'Shooter');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (83, 'League of Legends', 'Engage in intense multiplayer battles', 141.85, 'used', 'Sega Saturn', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (31, 'Half-Life', 'Master challenging puzzles', 353.01, 'used', 'Xbox', 'Sports');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (54, 'Metroid', 'Experience thrilling gameplay', 697.83, 'new', 'Nintendo Switch', 'Fighting');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (53, 'Tetris', 'Experience thrilling gameplay', 22.81, 'used', 'PC', 'Strategy');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (11, 'Minecraft', 'Master challenging puzzles', 464.58, 'used', 'Mobile', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (32, 'Mario Kart 64', 'Embark on an epic adventure', 16.0, 'new', 'PC', 'Shooter');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (53, 'Guitar Hero', 'Master challenging puzzles', 640.14, 'new', 'Xbox One', 'Strategy');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (32, 'Pac-Man', 'Unleash your inner hero', 493.03, 'used', 'PlayStation 2', 'Arcade');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (28, 'Rayman', 'Master challenging puzzles', 769.26, 'new', 'Xbox', 'Strategy');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (46, 'The Elder Scrolls V: Skyrim', 'Experience thrilling gameplay', 772.68, 'new', 'Sega Saturn', 'Platformer');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (38, 'GoldenEye 007', 'Engage in intense multiplayer battles', 397.22, 'new', 'Xbox', 'Fighting');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (30, 'Crash Team Racing', 'Unleash your inner hero', 140.59, 'new', 'Xbox One', 'Fighting');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (6, 'League of Legends', 'Embark on an epic adventure', 693.41, 'used', 'Nintendo 64', 'Puzzle');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (43, 'Guitar Hero', 'Engage in intense multiplayer battles', 178.25, 'new', 'Nintendo Switch', 'Action');
insert into ads (user_id, title, description, price, `condition`, platform, genre) values (13, 'Super Mario Kart', 'Immerse yourself in a captivating world', 102.02, 'used', 'Mobile', 'Adventure');
